### ISSUE TITLE
libzimg compatibility

### ISSUE THREAD

**Issue by darealshinji** [HomeOfVapourSynthEvolution/VapourSynth-waifu2x-opt#1]
I was able to build and link this plugin against zimg [v1.1.1](https://github.com/sekrit-twc/zimg/releases/tag/release-1.1.1), but it doesn't build when I use newer versions (2.x).
I think this should either be mentioned in the README or the code should be updated to work with the newest zimg version.

**Comment by mawen1250** [comment]
Yeah it uses zimg API v1.
This plugin is deprecated since there's waifu2x-w2xc and waifu2x-caffe for VapourSynth now, thus I won't touch it any more.
Anyway I will update the README later.

**Comment by darealshinji** [comment]
Thanks for updating the README.
